# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created: Sun Mar 28 18:08:29 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(780, 585)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.question_type_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setWeight(75)
        font.setBold(True)
        self.question_type_label.setFont(font)
        self.question_type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.question_type_label.setObjectName("question_type_label")
        self.horizontalLayout_2.addWidget(self.question_type_label)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.line_seperator = QtGui.QFrame(self.centralwidget)
        self.line_seperator.setFrameShape(QtGui.QFrame.HLine)
        self.line_seperator.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_seperator.setObjectName("line_seperator")
        self.gridLayout.addWidget(self.line_seperator, 1, 0, 1, 1)
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtGui.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.qa_layout = QtGui.QVBoxLayout(self.layoutWidget)
        self.qa_layout.setObjectName("qa_layout")
        self.question_textbrowser = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question_textbrowser.sizePolicy().hasHeightForWidth())
        self.question_textbrowser.setSizePolicy(sizePolicy)
        self.question_textbrowser.setFocusPolicy(QtCore.Qt.NoFocus)
        self.question_textbrowser.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.question_textbrowser.setObjectName("question_textbrowser")
        self.qa_layout.addWidget(self.question_textbrowser)
        spacerItem = QtGui.QSpacerItem(20, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.qa_layout.addItem(spacerItem)
        self.answer_type_label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setWeight(75)
        font.setBold(True)
        self.answer_type_label.setFont(font)
        self.answer_type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.answer_type_label.setObjectName("answer_type_label")
        self.qa_layout.addWidget(self.answer_type_label)
        self.answer_lineedit = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.answer_lineedit.setFont(font)
        self.answer_lineedit.setObjectName("answer_lineedit")
        self.qa_layout.addWidget(self.answer_lineedit)
        self.progress_hint_layout = QtGui.QHBoxLayout()
        self.progress_hint_layout.setObjectName("progress_hint_layout")
        self.progress_bar = QtGui.QProgressBar(self.layoutWidget)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.progress_hint_layout.addWidget(self.progress_bar)
        self.hint_button = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hint_button.sizePolicy().hasHeightForWidth())
        self.hint_button.setSizePolicy(sizePolicy)
        self.hint_button.setObjectName("hint_button")
        self.progress_hint_layout.addWidget(self.hint_button)
        self.qa_layout.addLayout(self.progress_hint_layout)
        self.layoutWidget1 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.given_answers_layout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.given_answers_layout.setObjectName("given_answers_layout")
        self.given_answers_textbrowser = QtGui.QTextBrowser(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.given_answers_textbrowser.sizePolicy().hasHeightForWidth())
        self.given_answers_textbrowser.setSizePolicy(sizePolicy)
        self.given_answers_textbrowser.setBaseSize(QtCore.QSize(0, 0))
        self.given_answers_textbrowser.setFocusPolicy(QtCore.Qt.NoFocus)
        self.given_answers_textbrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.given_answers_textbrowser.setMidLineWidth(0)
        self.given_answers_textbrowser.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.given_answers_textbrowser.setObjectName("given_answers_textbrowser")
        self.given_answers_layout.addWidget(self.given_answers_textbrowser)
        spacerItem1 = QtGui.QSpacerItem(20, 157, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.given_answers_layout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.splitter_2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuRehearse = QtGui.QMenu(self.menubar)
        self.menuRehearse.setObjectName("menuRehearse")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSwitchUserLanguage = QtGui.QAction(MainWindow)
        self.actionSwitchUserLanguage.setObjectName("actionSwitchUserLanguage")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionProgress = QtGui.QAction(MainWindow)
        self.actionProgress.setObjectName("actionProgress")
        self.actionOptions = QtGui.QAction(MainWindow)
        self.actionOptions.setCheckable(False)
        self.actionOptions.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionOptions.setMenuRole(QtGui.QAction.PreferencesRole)
        self.actionOptions.setPriority(QtGui.QAction.NormalPriority)
        self.actionOptions.setObjectName("actionOptions")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setMenuRole(QtGui.QAction.AboutRole)
        self.actionAbout.setObjectName("actionAbout")
        self.actionVocabulary = QtGui.QAction(MainWindow)
        self.actionVocabulary.setCheckable(True)
        self.actionVocabulary.setChecked(True)
        self.actionVocabulary.setObjectName("actionVocabulary")
        self.actionJapanese = QtGui.QAction(MainWindow)
        self.actionJapanese.setObjectName("actionJapanese")
        self.actionType = QtGui.QAction(MainWindow)
        self.actionType.setObjectName("actionType")
        self.actionLanguage_2 = QtGui.QAction(MainWindow)
        self.actionLanguage_2.setObjectName("actionLanguage_2")
        self.actionVocabulary_2 = QtGui.QAction(MainWindow)
        self.actionVocabulary_2.setCheckable(True)
        self.actionVocabulary_2.setChecked(True)
        self.actionVocabulary_2.setObjectName("actionVocabulary_2")
        self.actionDatabase = QtGui.QAction(MainWindow)
        self.actionDatabase.setObjectName("actionDatabase")
        self.menuFile.addAction(self.actionSwitchUserLanguage)
        self.menuFile.addAction(self.actionExit)
        self.menuOptions.addAction(self.actionProgress)
        self.menuOptions.addAction(self.actionDatabase)
        self.menuOptions.addAction(self.actionOptions)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuRehearse.addAction(self.actionVocabulary_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuRehearse.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.answer_lineedit, self.hint_button)
        MainWindow.setTabOrder(self.hint_button, self.question_textbrowser)
        MainWindow.setTabOrder(self.question_textbrowser, self.given_answers_textbrowser)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.question_type_label.setText(QtGui.QApplication.translate("MainWindow", "Japanese: Vocabulary", None, QtGui.QApplication.UnicodeUTF8))
        self.question_textbrowser.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600;\">Question</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.answer_type_label.setText(QtGui.QApplication.translate("MainWindow", "Meaning", None, QtGui.QApplication.UnicodeUTF8))
        self.answer_lineedit.setText(QtGui.QApplication.translate("MainWindow", "Type translation here", None, QtGui.QApplication.UnicodeUTF8))
        self.hint_button.setText(QtGui.QApplication.translate("MainWindow", "Hint", None, QtGui.QApplication.UnicodeUTF8))
        self.hint_button.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+/", None, QtGui.QApplication.UnicodeUTF8))
        self.given_answers_textbrowser.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; text-decoration: line-through;\">Given answers</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRehearse.setTitle(QtGui.QApplication.translate("MainWindow", "Rehearse", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSwitchUserLanguage.setText(QtGui.QApplication.translate("MainWindow", "Switch User/Language", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionProgress.setText(QtGui.QApplication.translate("MainWindow", "Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptions.setText(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVocabulary.setText(QtGui.QApplication.translate("MainWindow", "Vocabulary", None, QtGui.QApplication.UnicodeUTF8))
        self.actionJapanese.setText(QtGui.QApplication.translate("MainWindow", "Japanese", None, QtGui.QApplication.UnicodeUTF8))
        self.actionType.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLanguage_2.setText(QtGui.QApplication.translate("MainWindow", "Language", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVocabulary_2.setText(QtGui.QApplication.translate("MainWindow", "Vocabulary", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDatabase.setText(QtGui.QApplication.translate("MainWindow", "Database", None, QtGui.QApplication.UnicodeUTF8))

